# Generated by Django 5.1.7 on 2025-03-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('variety', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_id', models.CharField(max_length=255)),
            ],
        ),
    ]
