# Generated by Django 5.1.7 on 2025-03-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='seller_name',
        ),
    ]
